### ISSUE TITLE
패키지 의존성 관련 내부 기능 사용 문의

### ISSUE THREAD

**Issue by hnlee77** [hnlee77/ApproximateDPs.jl#1]
`ApproximateDPs.jl` 에서 소스파일 이동 중에 기존 `FlightSims`에 정의되었던 utils를 사용이 필요한 것을 발견하였습니다.
의존성을 두지 않고 사용할 수 있는 좋은 방안이 있을지 궁금합니다.

**Comment by JinraeKim** [comment]
아직 확정은 아니나, 제가 제안하는 방향은 [FlightGNC.jl](https://github.com/nhcho91/FlightGNC.jl/issues/3) 에 제안한 것과 유사합니다.

1) ApproximateDPs.jl 는 FSim-like 의존성을 갖지 않는다.
2) 필요할 경우 FSimZoo.jl 에 FSim-compatible 한 ApproximateDPs.jl 의 기능을 구현한다.

우선, FlightSims.jl 의 utils 중 어떤 기능이 필요한가요?

**Comment by hnlee77** [comment]
Polynomial basis 구성을 위한 utils가 필요했습니다~
