### ISSUE TITLE
패키지 사용 관련 헷갈리는 부분에 대한 질문

### ISSUE THREAD

**Issue by hnlee77** [hnlee77/ApproximateDPs.jl#19]
@JinraeKim 에게 물어볼 것이 있습니다.
`FSimZoo` 소스파일에 보면 `using FSimBase`를 하고 있습니다.
그러면 `FSimZoo` 패키지를 사용하면 `FSimBase`도 함께 사용하는 것이라고 생각이 되는데요...
`FSimBase`를 사용하려고 하니 정의되어 있지 않다고 오류가 납니다.

1. `using FSimZoo` 를 하면 `using FSimBase`가 포함된 것으로 봐도 될까요?
2. 만약 그렇다면 `using FSimZoo`를 했을 때 `FSimBase` 가 없는것이 잘 이해되지 않습니다...

**Comment by JinraeKim** [comment]
@hnlee77 
Please share your code (or trials in REPL) and REPL outputs (e.g., error messages).

**Comment by hnlee77** [comment]
This is REPL example.
```
julia> using FSimZoo

julia> FSimZoo
FSimZoo

julia> FSimBase
ERROR: UndefVarError: FSimBase not defined
```

**Comment by JinraeKim** [comment]
1) `FSimBase` is a package; I don't think it can be exported as a standalone method.
2) What are you trying to do?
