### ISSUE TITLE
integrated environments 사용 문의

### ISSUE THREAD

**Issue by hnlee77** [hnlee77/ApproximateDPs.jl#2]
기존에 `FlightSims`에서 정의되었던 env들 (integrated environments 포함)이 `FSimZoo`로 이동된 것으로 보여집니다. 그런데 이것들을 어떻게 불러와서 사용할 수 있을지 잘 모르겠습니다.

**Comment by JinraeKim** [comment]
FSimZoo.jl 로 이전되었으나, FlightSims.jl 에서도 export 됩니다.

별개로, [#1, comment](https://github.com/hnlee77/ApproximateDPs.jl/issues/1#issuecomment-927544563) 에서 언급하였듯이 이 패키지의 소스파일들은 FSim 의 환경 등의 의존성을 갖지 않는 것이 좋겠습니다.

물론 FSim 을 이용해서 편리하게 테스트를 하고 싶을 수 있겠죠? 그럴때는 `using FlightSims` 혹은 `using FSimZoo` 를 하면 됩니다
