### ISSUE TITLE
기존 FlightSims 기능 관련 오류

### ISSUE THREAD

**Issue by hnlee77** [hnlee77/ApproximateDPs.jl#20]
작성한 알고리즘에 다음과 같은 내용이 있습니다.

```
    FlightSims.save(file_path, env, prob, sol)
```

그런데 지금은 `FlightSims`에서 이 기능이 사라진 것으로 보입니다. 
어떤 함수를 쓰면 될까요?

**Comment by JinraeKim** [comment]
BTW, is it necessary?

**Comment by hnlee77** [comment]
Yes, because, in the `continuous_time_vi_adp` method, it is necessary that saving data files and reading it.

**Comment by hnlee77** [comment]
> `FlightSims.save` has been deprecated. Let's try other saving tools, e.g., [JLD2](https://github.com/JuliaIO/JLD2.jl) if necessary.

Thanks.

**Comment by JinraeKim** [comment]
@hnlee77
For now, use JLD2.jl or just reproduce and use the data every time :)
