### ISSUE TITLE
`FlightSims` 패키지 local dev 패키지의 master tracking

### ISSUE THREAD

**Issue by hnlee77** [hnlee77/ApproximateDPs.jl#3]
가상환경에 설치된 `FlightSims` 패키지가 local dev 에 다운로드 되어있는 깃헙의 master 를 tracking 하도록 하고 싶습니다.
`dev FlightSims`명령어를 쓰면 이것이 가능한 것 같은데, 다음과 같은 오류가 납니다..
```
(@v1.6) pkg> dev FlightSims
Path `/Users/hanna/.julia/dev/FlightSims` exists and looks like the correct package. Using existing path.
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package FSimZoo [e2d5807d]:
 FSimZoo [e2d5807d] log:
 ├─FSimZoo [e2d5807d] has no known versions!
 └─restricted to versions 0.1 by FlightSims [a4c2f6ca] — no versions left
   └─FlightSims [a4c2f6ca] log:
     ├─possible versions are: 0.10.0 or uninstalled
     └─FlightSims [a4c2f6ca] is fixed to version 0.10.0
```

**Comment by JinraeKim** [comment]
[현재 FSimZoo.jl 이 Juila Register 에 등록되지 않아서](https://github.com/JinraeKim/FSimZoo.jl/commit/ae6c4cad77033afffceeb08986247d93f55e398a) 생기는 이슈로, FSimZoo 도 직접 받아서 dev 화하면 될듯.

**Comment by hnlee77** [comment]
`FlightSims`에 `FSimZoo`의 기능이 모두 포함되어 있음

**Comment by JinraeKim** [comment]
`Pkg.dev` 명령어에서 경로를 정해줄 수 있었던 것 같아요. 찾아보세요~

**Comment by hnlee77** [comment]
이 [사이트](https://pkgdocs.julialang.org/v1.1/managing-packages/#Adding-packages-1)에서 찾아보았으나 경로를 정해주는 것은 잘 모르겠습니다.. 일단 add 도 안되는 상황이라서 0.10.0으로 버전 업 후에 다시 시도해보겠습니다.

**Comment by JinraeKim** [comment]
> 이 [사이트](https://pkgdocs.julialang.org/v1.1/managing-packages/#Adding-packages-1)에서 찾아보았으나 경로를 정해주는 것은 잘 모르겠습니다.. 일단 add 도 안되는 상황이라서 0.10.0으로 버전 업 후에 다시 시도해보겠습니다.

님 링크 버전 1.1.3인데요...? ㅠ

[이거](https://docs.julialang.org/en/v1/stdlib/Pkg/) 참고하십쇼

**Comment by hnlee77** [comment]
ㅎ.. 그렇군요.. 알려주신 사이트를 참고해봤지만 같은 오류가 납니다.
```
(@v1.6) pkg> develop --local FlightSims
[ Info: Resolving package identifier `FlightSims` as a directory at `~/.julia/dev/FlightSims`.
Path `FlightSims` exists and looks like the correct package. Using existing path.
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package FSimZoo [e2d5807d]:
 FSimZoo [e2d5807d] log:
 ├─FSimZoo [e2d5807d] has no known versions!
 └─restricted to versions 0.1 by FlightSims [a4c2f6ca] — no versions left
   └─FlightSims [a4c2f6ca] log:
     ├─possible versions are: 0.10.0 or uninstalled
     └─FlightSims [a4c2f6ca] is fixed to version 0.10.0
```
버전업을 기다려보겠습니다 ㅎ

**Comment by hnlee77** [comment]
호환성때문에 아예 레포 tracking 자체가 안되는 것 같습니다.

**Comment by JinraeKim** [comment]
@hnlee77 
[경로 참조하는거](https://discourse.julialang.org/t/workflow-for-local-package-testing/50854/4?u=ihany) 참고

**Comment by hnlee77** [comment]
버전업(0.10.0)과 함께 해결
